export const API_URLS = {
  LOGIN: '/auth',
  USER_OTP: '/user-otp',
  FORGOT_PASSWORD: '/user-reset-password',
  USER: '/user',
  USER_CATEGORIES: '/user-categories',
  USER_BILLING_CYCLES: '/user-billing-cycles',
  CATALOGS: '/catalogs',
  USER_CONVERSATION: '/user-conversation',
  WORKOUT: '/workout',
  WORKOUT_SUBSCRIBED: '/workout/subscribed',
  WORKOUT_RATINGS: '/workout-ratings',
  WORKOUT_FAVORITES: '/workout-favorites',
  WORKOUT_LIKES: '/workout-likes',
  USER_GOALS: '/user-goals',
  SUSCRIPTIONS: '/subscriptions',
  FAQS: '/faqs',
  PAYMENTS: '/payments',
  APP_RATINGS: '/app-ratings',
};
